first_app/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from registration.backends.simple.views import RegistrationView


# Create a new class that redirects the user to the index page, if successful at logging
class MyRegistrationView(RegistrationView):
    def get_success_url(self, request, user):
        return '/rango/'

urlpatterns = [
    url(r'^rango/', include('rango.urls', namespace='rango')),
    url(r'^admin/', admin.site.urls),
    # url(r'^accounts/', include('registration.backends.simple.urls')),
    # url(r'^accounts/register/$', MyRegistrationView.as_view(), name='registration_register'),

]

rango/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^about/$', views.about, name='about'),
    url(r'^add_category/$', views.add_category, name='add_category'),
    url(r'^category/(?P<category_id>\d+)/$',
        views.get_category, name='category'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^restricted/$', views.restricted, name='restricted'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^add_page/$', views.add_page, name='add_page'),
    # url(r'^add_page/(?P<category_id>\d+)/$',
    #     views.add_page, name='add_page'),
    # url(r'^goto/$', views.track_url, name='goto'),


]

rango/models.py
from __future__ import unicode_literals
from django.template.defaultfilters import slugify
from django.db import models
from django.contrib.auth.models import User


class Category(models.Model):
    name = models.CharField(max_length=200, unique=True)
    likes = models.IntegerField(default=0)
    views = models.IntegerField(default=0)
    slug = models.SlugField()

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    def __str__(self):
        return self.name


class Page(models.Model):
    category = models.ForeignKey(Category)
    title = models.CharField(max_length=200)
    url = models.URLField()
    views = models.IntegerField(default=0)

    def __st__(self):
        return self.title


class UserProfile(models.Model):
    """User Progfile Model """
    user = models.OneToOneField(User)
    website = models.URLField(blank=True)
    # picture = models.ImageField(upload_to='images/', blank=True)

    def __str__(self):
        return self.user.username

rango/forms.py
from django import forms
from .models import Category, Page, UserProfile
# from django.forms import ModelForm
from django.contrib.auth.models import User


class CategoryForm(forms.ModelForm):

    class Meta:
        model = Category
        fields = ['name', ]


class PageForm(forms.ModelForm):

    class Meta:
        model = Page
        exclude = ['category', ]


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class UserProfileForm(forms.ModelForm):

    class Meta:
        model = UserProfile
        fields = ('website',)

rango/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from .models import Category, Page
from .forms import CategoryForm, UserProfileForm, UserForm, PageForm
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
# from django.views.generic.edit import CreateView


def index(request):
    # request.session.set_test_cookie() #Test Cookie Code
    category_list = Category.objects.order_by('-likes')[:5]
    context = {'categories': category_list}
    return render(request, 'index.html', context)


def get_category(request, category_id=4):
    try:

        context_dict = {}
        category = Category.objects.get(id=category_id)
        page = Page.objects.filter(category=category)
        context_dict['pages'] = page  # page , pages
        context_dict['category'] = category

    except Category.DoesNotExist:
        pass
    return render(request, 'category.html', context_dict)


def about(request):
    return render(request, 'about.html')


def add_category(request):
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return index(request)
        else:
            print(form.errors)
    else:
        form = CategoryForm()

    return render(request, 'add_category.html', {'form': form})


def add_page(request, page_id=4):
    try:
        cat = Category.objects.get(page_id)
    except Category.DoesNotExist:
        cat = None
    if request.method == 'POST':
        form = PageForm(request.POST)
        if form.is_valid():
            if cat:
                page = form.save(commit=True)
                page.category = cat
                page.views = 0
                page.save()
                return get_category(request, page_id)
        else:
            print(form.errors)
    else:
        form = PageForm()
    context_dict = {'form': form, 'category': cat}
    return render(request, 'add_page.html', context_dict)

    # if request.method == 'POST':
    #     page_form = PageForm(request.POST)
    #     if page_form.is_valid():
    #         page_form.save(commit=True)
    #         return index(request)
    #     else:
    #         print(page_form.errors)
    # else:
    #     page_form = PageForm()

#    return render(request, 'add_page.html', {'page_form': page_form})


def register(request):
    # Test Cookie Code
    # if request.session.test_cookie_worked():
    #     print ('>>>TEST COOKIE Worked')
    #     request.session.delete_test_cookie()

    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        user_profile = UserProfileForm(data=request.POST)

        if user_form.is_valid() and user_profile.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            # if 'picture' in request.FILES:  # Install pillow , python3-dev
            #     profile.picture = request.FILES['picture']
            #     profile.save()
            #     registered = True
        else:
            print(user_form.errors, user_profile.errors)
    else:
        user_form = UserForm()
        user_profile = UserProfileForm()

    return render(request, 'register.html',
                  {'user_form': user_form,
                   'user_profile': user_profile,
                   'registered': registered})


def user_login(request):

    if request.method == 'POST':

        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)

        if user:

            if user.is_active:
                login(request, user)
                return HttpResponseRedirect('/rango/')
            else:
                return HttpResponse("User Not Active Right Now...! ")
        else:
            print(
                "Invalid User Name Or password : {0}, {1}"
                .format(username, password))
            return HttpResponse("Invalid Login details.")
    else:
        return render(request, 'login.html', {})


@login_required
def restricted(request):
    return HttpResponse(
        "as long as you see this message So you are logged in :) شاطر"
    )


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect('/rango/')


# def track_url(request):
#     page_id = None
#     url = '/rango/'
#     if request.method == 'GET':
#         if 'page_id' in request.GET:
#             page_id = request.GET['page_id']
#             try:
#                 page = Page.objects.get(id=page_id)
#                 page.views = page.views+1
#                 page.save()
#                 url = page.url
#             except:
#                 pass
#     return redirect(url)

templates/about.html
{% extends "base.html" %}

{% load staticfiles %}

{% block title %}About{% endblock %}

{% block body_block %}
    <div class="page-header">
                <h1>About</h1>
            </div>
            <div>
            <p></strong>.</p>

            <img  width="90" height="100" src="{% static "naroto.jpg" %}" alt="Picture of Rango" />
            </div>
{% endblock %}

templates/add_category.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}Add Category{% endblock title %}
{% block body_block %}
    
        <h1>Add a Category</h1>

        <form role="form"  id="CategoryForm" method="post" action=".">
            {% csrf_token %}
            {{ form.as_p }}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}

            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}<br/>
                {{ field }}<br/>
            {% endfor %}
            <br/>
            <a href="{% url 'rango:index' %}"></a> <button class="btn btn-primary" type="submit" name="submit">Add Category</button>
        </form>
        
{% endblock body_block %}

templates/add_page.html
{% extends 'base.html' %}

{% block title %}Add Page{% endblock %}


{% block body_block %}

<form role="form"  id="PageForm" method="post" action=".">
    <h2 class="form-signin-heading">Add a Page to <a href="{% url 'rango:category' %}"> {{ category.name }}</a></h2>
    {% csrf_token %}
    {% for hidden in page_form.hidden_fields %}
        {{ hidden }}
    {% endfor %}

    {% for field in page_form.visible_fields %}
        {{ field.errors }}
        {{ field.help_text }}<br/>
        {{ field }}<br/>
    {% endfor %}

    <br/>
    <button class="btn btn-primary" type="submit" name="submit">Add Page</button>
</form>


{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="icon" href="http://getbootstrap.com/favicon.ico">

  <title>Rango - {% block title %}How to Tango with Django!{% endblock %}</title>

  <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
  <link href="{% static "css/dashboard.css" %}" rel="stylesheet">


     <!--[if lt IE 9]>
      <script src="/static/javascript/html5shiv.min.js"></script>
      <script src="/static/javascript/respond.min.js"></script>
      <![endif]-->
    </head>

    <body>

      <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/rango/">Rango</a>
          </div>
          <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
              <li><a href="{% url 'rango:index' %}">Home</a></li>
              {% if user.is_authenticated %}
              <li><a href="{% url 'rango:restricted' %}">Restricted Page</a></li>
              <li><a href="{% url 'rango:logout' %}?next=/rango/">Logout</a></li>
              <li><a href="{% url 'rango:add_category' %}">Add a New Category</a></li>
              {% else %}
              <li><a href="{% url 'rango:register' %}">Register</a></li>
              <li><a href="{% url 'rango:login' %}">Login</a></li>
              {% endif %}
              <li><a href="{% url 'rango:about' %}">About</a></li>

            </ul>
          </div>
        </div>
      </div>

      <div class="container-fluid">
        <div class="row">
          <div class="col-sm-3 col-md-2 sidebar">

            {% block side_block %}{% endblock %}

          </div>
          <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
           <div>
            {% block body_block %}{% endblock %}
          </div>
        </div>
      </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static "javascript/jquery.min.js" %}"></script>
    <script src="{% static "javascript/bootstrap.min.js" %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static "javascript/ie10-viewport-bug-workaround.js" %}"></script>
  </body>
  </html>

templates/category.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}{{ category_name }}{% endblock %}

{% block body_block %}
    <h1>{{ category_name }}</h1>
    {% if category %}
        {% if pages %}
        <ul>
                {% for page in pages %}
                <li><a href="{{ page.url }}">{{ page.title }}</a></li>
                {% endfor %}
                </ul>
        {% else %}
                <strong>No pages currently in category.</strong>
                {% endif %}

        {% if user.is_authenticated %}
                <a href="{% url 'rango:add_page' %}">Add a Page</a>
                {% endif %}
        {% else %}
                 The specified category {{ category_name }} does not exist!
    {% endif %}

{% endblock %}

templates/index.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}Index{% endblock title %}
{% block body_block %}
        
{% if user.is_authenticated %}
        <div class="page-header">
        <h1><strong>Rango say... Hello {{ user.username }}</strong></h1>
        {% else %}
        <h1>Rango say... Hello World!</h1>         
{% endif %}
        </div>

        <div class="panel panel-primary">
    <div class="panel-heading" style="background-color:#ddd;">
            <h3 class="panel-title">Categories</h3>
            {% if categories %}
               <ul>
               {% for category in categories %}
               <li><a href="{% url 'rango:category' category.id %}">{{ category.name }}</a></li>       
               {% endfor %}
               </ul>
               {% else %}
               <strong>There is No Categories present.</strong> 
               {% endif %}
            </div>
        </div>

         <div class="panel panel-primary">
            <div class="panel-heading">
                    <h3 class="panel-title">Pages</h3>
              {% if pages %}
              <u>
                      {% for page in pages %}
                      <li><a href="{{ page.url }}">{{ page.title }}</a></li>       
                      {% endfor %}
              </u>
              {% else %}
              <strong>There is No pages in this Category </strong>      
              {% endif %}
            </div>
    </div>
{% endblock body_block %}

templates/login.html
{% extends "base.html" %}
{% load staticfiles %}
{% block body_block %}
	<link href="/static/css/signin.css" rel="stylesheet">
	<form class="form-signin" role="form" method="post" action=".">
		<h1><p><strong>Login to Rango</strong></p></h1>
		<form id="login_form" method="POST" action="/rango/login/">
			{% csrf_token %}
			<h2 class="form-signin-heading">Please sign in</h2>
			<input class="form-control" placeholder="Username" id="id_username" maxlength="254" name="username" type="text" required autofocus=""/>
			<input type="password" class="form-control" placeholder="Password" id="id_password" name="password"  required />

        <button class="btn btn-lg btn-primary btn-block" type="submit" value="Submit" >Sign in</button>
        </form>
		</form>
		
{% endblock body_block %}

templates/register.html
{% extends "base.html" %}


{% block body_block %}
<form role="form"  method="post" action=".">
	{% csrf_token %}

	<h2 class="form-signin-heading">Sign Up Here</h2>

	<div class="form-group" >
		<p class="required"> <label for="id_username">Username:</label>
			<input class="form-control"  id="id_username" maxlength="30" name="username" type="text"  placeholder="Enter username"/></p>
		</div>
		<div class="form-group">
			<p class="required"><label for="id_email">E-mail:</label>
				<input class="form-control" id="id_email" name="email" type="email" placeholder="Enter email" /></p>
			</div>
			<div class="form-group">
				<p class="required"><label for="id_password1">Password:</label>
					<input class="form-control" id="id_password1" name="password1" type="password" placeholder="Enter password" /></p>
				</div>
				<div class="form-group">
					<p class="required"><label for="id_password2">Password (again):</label>
						<input class="form-control" id="id_password2" name="password2" type="password" placeholder="Enter password again" /></p>
				</div>

					<button type="submit" class="btn btn-default">Submit</button>

</form>
{% endblock %}